//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace facturaElectronica.DIAN.Recepcion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura", ConfigurationName="DIAN.Recepcion.facturaElectronicaPortName")]
    public interface facturaElectronicaPortName {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación EnvioFacturaElectronica no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronicaRespuesta EnvioFacturaElectronica(facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronicaPeticion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronicaRespuesta> EnvioFacturaElectronicaAsync(facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronicaPeticion request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura")]
    public partial class EnvioFacturaElectronica : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nITField;
        
        private string invoiceNumberField;
        
        private System.DateTime issueDateField;
        
        private byte[] documentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NIT {
            get {
                return this.nITField;
            }
            set {
                this.nITField = value;
                this.RaisePropertyChanged("NIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
                this.RaisePropertyChanged("InvoiceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
                this.RaisePropertyChanged("IssueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("Document");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura")]
    public partial class ReceivedInvoice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroFacturaField;
        
        private string uUIDField;
        
        private int responseField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumeroFactura {
            get {
                return this.numeroFacturaField;
            }
            set {
                this.numeroFacturaField = value;
                this.RaisePropertyChanged("NumeroFactura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("Comments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura")]
    public partial class AcuseRecibo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReceivedInvoice receivedInvoiceField;
        
        private string versionField;
        
        private System.DateTime receivedDateTimeField;
        
        private System.DateTime responseDateTimeField;
        
        private int responseField;
        
        private string commentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReceivedInvoice ReceivedInvoice {
            get {
                return this.receivedInvoiceField;
            }
            set {
                this.receivedInvoiceField = value;
                this.RaisePropertyChanged("ReceivedInvoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ReceivedDateTime {
            get {
                return this.receivedDateTimeField;
            }
            set {
                this.receivedDateTimeField = value;
                this.RaisePropertyChanged("ReceivedDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ResponseDateTime {
            get {
                return this.responseDateTimeField;
            }
            set {
                this.responseDateTimeField = value;
                this.RaisePropertyChanged("ResponseDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("Comments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioFacturaElectronicaPeticion {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioFacturaElectronicaPeticion", Namespace="http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura", Order=0)]
        public facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronica EnvioFacturaElectronicaPeticion1;
        
        public EnvioFacturaElectronicaPeticion() {
        }
        
        public EnvioFacturaElectronicaPeticion(facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronica EnvioFacturaElectronicaPeticion1) {
            this.EnvioFacturaElectronicaPeticion1 = EnvioFacturaElectronicaPeticion1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioFacturaElectronicaRespuesta {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioFacturaElectronicaRespuesta", Namespace="http://www.dian.gov.co/servicios/facturaelectronica/ReportarFactura", Order=0)]
        public facturaElectronica.DIAN.Recepcion.AcuseRecibo EnvioFacturaElectronicaRespuesta1;
        
        public EnvioFacturaElectronicaRespuesta() {
        }
        
        public EnvioFacturaElectronicaRespuesta(facturaElectronica.DIAN.Recepcion.AcuseRecibo EnvioFacturaElectronicaRespuesta1) {
            this.EnvioFacturaElectronicaRespuesta1 = EnvioFacturaElectronicaRespuesta1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface facturaElectronicaPortNameChannel : facturaElectronica.DIAN.Recepcion.facturaElectronicaPortName, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class facturaElectronicaPortNameClient : System.ServiceModel.ClientBase<facturaElectronica.DIAN.Recepcion.facturaElectronicaPortName>, facturaElectronica.DIAN.Recepcion.facturaElectronicaPortName {
        
        public facturaElectronicaPortNameClient() {
        }
        
        public facturaElectronicaPortNameClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public facturaElectronicaPortNameClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public facturaElectronicaPortNameClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public facturaElectronicaPortNameClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronicaRespuesta facturaElectronica.DIAN.Recepcion.facturaElectronicaPortName.EnvioFacturaElectronica(facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronicaPeticion request) {
            return base.Channel.EnvioFacturaElectronica(request);
        }
        
        public facturaElectronica.DIAN.Recepcion.AcuseRecibo EnvioFacturaElectronica(facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronica EnvioFacturaElectronicaPeticion1) {
            facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronicaPeticion inValue = new facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronicaPeticion();
            inValue.EnvioFacturaElectronicaPeticion1 = EnvioFacturaElectronicaPeticion1;
            facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronicaRespuesta retVal = ((facturaElectronica.DIAN.Recepcion.facturaElectronicaPortName)(this)).EnvioFacturaElectronica(inValue);
            return retVal.EnvioFacturaElectronicaRespuesta1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronicaRespuesta> facturaElectronica.DIAN.Recepcion.facturaElectronicaPortName.EnvioFacturaElectronicaAsync(facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronicaPeticion request) {
            return base.Channel.EnvioFacturaElectronicaAsync(request);
        }
        
        public System.Threading.Tasks.Task<facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronicaRespuesta> EnvioFacturaElectronicaAsync(facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronica EnvioFacturaElectronicaPeticion1) {
            facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronicaPeticion inValue = new facturaElectronica.DIAN.Recepcion.EnvioFacturaElectronicaPeticion();
            inValue.EnvioFacturaElectronicaPeticion1 = EnvioFacturaElectronicaPeticion1;
            return ((facturaElectronica.DIAN.Recepcion.facturaElectronicaPortName)(this)).EnvioFacturaElectronicaAsync(inValue);
        }
    }
}
